### ISSUE TITLE
1.19 server crash

### ISSUE THREAD

**Issue by PTOM76** [Kneelawk/WiredRedstone#10]
Log: https://pastebin.com/JaC3Vdaa

it could fix by adding "@Environment(EnvType.CLIENT)" to loadClient() of CoreMinecraftNetUtil of LibNetworkStack.

**Comment by PTOM76** [comment]
Oh, maybe I should have submitted to LibNetworkStack's issue. Excuse me.

**Comment by Kneelawk** [comment]
I always forget to test something. Ha ha

**Comment by Kneelawk** [comment]
I'm trying to get this working, but I'm running into brutal registry-sync errors.

**Comment by Kneelawk** [comment]
Ok, turns out you need Polymer on 1.19 for fixing registry-sync issues in QSL.

**Comment by Kneelawk** [comment]
Ok, your suggestion seems to have fixed the LNS issue and I have tested Wired Redstone working on a dedicated client and server setup. I'll hopefully have a release of Wired Redstone that incorporates the LNS fix out shortly.

**Comment by Kneelawk** [comment]
I'll have the release out as soon as CurseForge fixes its outage.

I should probably look into separating my publishing scripts so if one site fails, I can still publish to the others.

**Comment by Kneelawk** [comment]
I'm re-opening this as I don't know when I'll get a chance to publish this.

**Comment by PTOM76** [comment]
thank you very much!

**Comment by Kneelawk** [comment]
This is fixed in release `v0.4.2+1.19`.

Modrinth: https://modrinth.com/mod/wiredredstone/version/0.4.2%2B1.19
CurseForge: https://www.curseforge.com/minecraft/mc-mods/wired-redstone/files/3869549
