### ISSUE TITLE
[1.18.2] Redstone Assembler does not have loot table or effective tool/mining speed

### ISSUE THREAD

**Issue by Notenoughmail** [Kneelawk/WiredRedstone#13]
Using v0.3.4 the Redstone Assembler does not drop itself (or anything) when broken and is able to be insta-mined with just an empty hand.

**Comment by Kneelawk** [comment]
Oops, can confirm, looks like block breaking does not work the way I thought it did. I should hopefully have a fix for this out soon.

**Comment by Kneelawk** [comment]
Ok, no, I just spaced when making this block.

**Comment by Kneelawk** [comment]
Ok, this should be fixed in `v0.3.5+1.18.2` and `v0.4.5+1.19` which are now out on Modrinth and CurseForge.
