### ISSUE TITLE
[1.18.2] Crash with Create contraptions

### ISSUE THREAD

**Issue by Mindtester** [Kneelawk/WiredRedstone#15]
Greetings!

Any gate receiving Redstone signal from Observer when contraption forms block after stop cause [crash](https://github.com/Kneelawk/WiredRedstone/files/9238923/issue.txt) and could prevent world from loading.

How to reproduce:
![out](https://user-images.githubusercontent.com/10900819/182289398-7a6e3ca6-ccf3-4655-b2d7-af8ff96ab19e.png)

WiredRedstone  v0.3.6
Create v0.4.1

**Comment by Kneelawk** [comment]
Hmm... It looks like multiparts don't appreciate being moved by Create contraptions.

**Comment by Mindtester** [comment]
That's sad. Any chances you will proxy Create calls and make your mod compatible with contraptions?

Btw, [Compact Machines](https://www.curseforge.com/minecraft/mc-mods/compact-machines-fabric) is out. Do you plan to add Redstone Tunnel for it?

**Comment by Kneelawk** [comment]
I'll need to see if Create has any kind of API for handling things like this. I do plan on trying to get this to work eventually, but it won't be easy.

Also, yes, I plan on adding wireless redstone receivers/transmitters much like those in WRCBE.

**Comment by Mindtester** [comment]
Well, Create has its own Latches and wireless so I hope it could be doable. Also [Logic Gates](https://www.curseforge.com/minecraft/mc-mods/logic-gates-fabric) works with contraptions. But I suppose due to its simplicity and vanilla-like nature that supported in Create by default.

Limitless cross-dimensional wireless is op imo. That's why I was interested in new Tunnel for this exact mod and I'm expecting that code behind such Tunnel would be the same as for receiver/transmitter and wouldn't be hard to implement. Probably in different mod.

Anyway I suppose this ticket should be closed as not directly related to WiredRedstone. And gonna wait for enhancement.

**Comment by Kneelawk** [comment]
This looks related to https://github.com/AlexIIL/LibMultiPart/issues/52. Minecraft needs a better system for rotating blocks. I've been considering making a library to work around this, but I'll need to talk it over with AlexIIL first.

**Comment by Mindtester** [comment]
Glad to hear it. Hope you with AlexIIL will come to proper solution.

**Comment by Kneelawk** [comment]
I've been making progress on this recently. I'm not quite to a point where I have something I can release yet, but I'm hoping that should be sometime in the near future.

**Comment by Kneelawk** [comment]
I now have a version of Wired Redstone for 1.18.2, that I'm about ready to release, that has this fixed.
