### ISSUE TITLE
[1.19.2] Sodium Issues

### ISSUE THREAD

**Issue by ghost** [Kneelawk/WiredRedstone#19]
Hi, I wanted to use [Iris shaders](https://www.curseforge.com/minecraft/mc-mods/irisshaders), so I needed [Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium).
When lauched my minecraft world with wires (and others) all of them was "missing" texture (test world screenshot below)
-

> _test-world screenshot_
> ![image](https://user-images.githubusercontent.com/106306104/189483992-61651730-b76e-4093-a1c3-4c7e873d9d02.png)
> Screnshot is Minecraft Quilt with only [Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium) and Wired Redstone loaded. No other mods, resourcepacks (etc)

Info
-
> Minecraft: _1.19.2 - Singleplayer_ 
> Quilt: _0.17.5 - Beta 2_
> OS: _Windows 11_
> Wired Redstone: _0.4.8_
> [Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium): _0.4.4, 0.4.3, 0.4.2_

**Comment by Kneelawk** [comment]
Did you also include [Indium](https://modrinth.com/mod/indium)? When using Sodium, Indium is also required for wires to render correctly.

I guess I didn't make it terribly clear Wired Redstone needs Indium on WR's mod page. I should probably do that.

**Comment by ghost** [comment]
Oh, okay, I'll try with indium, thanks <3
