### ISSUE TITLE
[Request] Adjustable energy storage and I/O values for the Redstone Assembler

### ISSUE THREAD

**Issue by xijtsjis** [Kneelawk/WiredRedstone#31]
The unchangeable 128k energy storage is a bit overkill for the pack I'm making. Adding a config of some kind to make the Assembler's energy properties adjustable to fit better into a pack's design would be appreciated.

**Comment by Kneelawk** [comment]
Good idea. I'll see if I can get this out shortly.

**Comment by Kneelawk** [comment]
That ended up being a bit more involved than I thought it would be, but hopefully I should have it out soon.

**Comment by xijtsjis** [comment]
Is 1.18 also doable? (Should've specified in the request, my bad.)
Doesn't look like anything's different in the relevant API bits between versions.

**Comment by Kneelawk** [comment]
Given that 1.18.2 came out almost a year ago, the 1.18.2 version of this mod is mainly in maintenance-only mode. However, the changes to get the config working look like they *probably* shouldn't be too hard to back-port, so I'll make an exception and backport it when I get the chance. But in general, backporting features is generally pretty low-priority.

**Comment by Kneelawk** [comment]
For more features as well as improved compatibility, I highly recommend you migrate to a newer version, as there are some significant bugfixes and compatibility-fixes that cannot be easily ported back to 1.18.2.

**Comment by Kneelawk** [comment]
Ok, a 1.18.2 version of this `0.3.11` should be out on MR and CF now.
