### ISSUE TITLE
Compatibility Check broken when using Velocity Proxy

### ISSUE THREAD

**Issue by KenzieMac130** [Kneelawk/WiredRedstone#33]
When using the velocity proxy with wired redstone the check that happens when a player logs onto the world always fails even if both client and server are in sync. 

![image](https://user-images.githubusercontent.com/7585719/219973650-c90454d8-c757-4ffc-809f-2a980f06575b.png)

Without using the velocity proxy this test works as expected and the user is allowed to join. (tested using LAN)

Tested using the following modpack https://github.com/KenzieMac130/KenziePack

**Comment by MattiDragon** [comment]
This is because you are using LOGIN phase networking. It's incompatible with proxies as you are already in the PLAY phase when connecting to the actual server

**Comment by Kneelawk** [comment]
Ok, I'll probably have a config option to switch the syncing to happen during PLAY phase instead of LOGIN phase, and another config option to just disable syncing entirely.

**Comment by Kneelawk** [comment]
Ok, this should be fixed in `v0.4.16+1.19.2` available on [Modrinth](https://modrinth.com/mod/wiredredstone/version/0.4.16%2B1.19.2) and [CurseForge](https://www.curseforge.com/minecraft/mc-mods/wired-redstone/files/4405092).
