### ISSUE TITLE
1.19.4 Client crash when trying to place Redstone Assembler on a block facing up or down.

### ISSUE THREAD

**Issue by cynthetic-boop** [Kneelawk/WiredRedstone#36]
`[02:46:06] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to down on Block{wiredredstone:redstone_assembler}, it is not an allowed value
	at net.minecraft.class_2688.method_11657(class_2688.java:130) ~[transformed-mod-minecraft.i0:0/:?]
	at com.kneelawk.wiredredstone.block.RedstoneAssemblerBlock.method_9605(RedstoneAssemblerBlock.kt:65) ~[transformed-mod-wiredredstone.i0:0/:?]`

Is the beginning of the stacktrace at the error.  Seems to be not handling how to orient the Redstone Assembler when facing up or down.  I have limited knowledge with Fabric modding, or else I would try to make a pull with this as well.

**Comment by Kneelawk** [comment]
Ok, should be fixed in version `0.6.1` on [Modrinth](https://modrinth.com/mod/wiredredstone/version/0.6.1+1.19.4) and [Curseforge](https://www.curseforge.com/minecraft/mc-mods/wired-redstone/files/4599242).
