### ISSUE TITLE
Bundled Cable support for CC: Restitched

### ISSUE THREAD

**Issue by SquidDev** [Kneelawk/WiredRedstone#4]
ComputerCraft/CC: Restitched has support for reading values directly from RedPower-esque bundled cables. However, it does not currently support WiredRedstone, as neither mod has compatibility for the other.

[The API for this is quite simple to implement](https://github.com/cc-tweaked/cc-restitched/blob/d03b68ecff092923e42a4f00617877cfdde03353/src/main/java/dan200/computercraft/api/ComputerCraftAPI.java#L168-L186), would you be interested in adding (or accepting a PR which added) support for it? Alternatively, compatibility can be added on CC:R's side, I just wasn't sure if you had a stable API we could interface with.

**Comment by Kneelawk** [comment]
Is there a way to set the bundled-cable input value on a computer?

Wired Redstone bundled cabled don't actually store their value, effectively only acting as a conduit for signals.

**Comment by SquidDev** [comment]
Ah, no. It's very much designed to be pull based, like vanilla redstone.

**Comment by Kneelawk** [comment]
How frequently does CC poll the state of attached bundled cables?

**Comment by SquidDev** [comment]
Poll based is possibly the wrong term. It behaves pretty much the same as most non-wire redstone components (i.e. lamps). Whenever it receives a block update on a given side, it then reads the redstone value of the adjacent block.

We also read the redstone values whenever a computer turns on/off, which can happen at fairly arbitrary points.

**Comment by Kneelawk** [comment]
Hmm, looks like the easiest way to implement this is to just start storing bundled cables' values in themselves and then just supply that when queried by CC.

Otherwise I end up with a lot of duplicated calculations and unnecessary updates.

**Comment by Kneelawk** [comment]
One thing to note is that Wired Redstone bundled cables actually support analog signals. I don't suppose it would be very easy to add support for these in CC: Restitched?

**Comment by Kneelawk** [comment]
For the time being, I'll probably just interpret a signal strength of `> 0` as an ON value and an ON value as a signal strength of 15.

**Comment by Kneelawk** [comment]
Ok, CC:R integration has been added. You can now read from and write to bundled cables using computers.

I'll close this issue once the feature is released.

**Comment by Kneelawk** [comment]
Oops. Looks like I forgot to close this when I made the release. This is now added in version 0.2.10.
