### ISSUE TITLE
Wires don't make an edge

### ISSUE THREAD

**Issue by SgtKaneki** [Kneelawk/WiredRedstone#40]
(Sorry for my bad english)

If you go up with an redstone wire, it doesn't make the typical edge as it should.
Maybe the screenshots says more than my words :D

https://imgur.com/cB2jKGY
https://imgur.com/1sZdTbD

**Comment by Kneelawk** [comment]
What version of Wired Redstone are you on?

**Comment by SgtKaneki** [comment]
0.7.1

**Comment by DemonSeedxp** [comment]
I'm seeing the same behavior on 0.7.0 1.20.1 with fabric 0.14.21
it does seem to make a connection and work properly but it just looks bad IMOP

btw, @SgtKaneki I believe the word you were looking for i the thread title was Corner , specifically it's the Inside Corner. The outside corner wraps around nicely, but the inside looks broken.

**Comment by hellozyemlya** [comment]
confirming, 0.7.1+1.20.1

**Comment by Kneelawk** [comment]
Given that it's purely visual, I have a pretty good idea what part of the code the bug is in. I'll try and fix it as soon as I get the chance.
