### ISSUE TITLE
Item-Drop doesn't work correct

### ISSUE THREAD

**Issue by SgtKaneki** [Kneelawk/WiredRedstone#42]
Mod Version: 0.7.2
Modloader: Fabric

Wire-Corners doesn't drop correctly when breaking it.
For example: To make a corner you need 2 wire's, but when you break it,  only 1 wire is dropping.

**Comment by Kneelawk** [comment]
How are you breaking the wires?

**Comment by SgtKaneki** [comment]
With a pickaxe

**Comment by SgtKaneki** [comment]
It seems to happen when the wire is on the bottom of a block

**Comment by Kneelawk** [comment]
I think I know what is happening. From my tests, the item will sometimes end up inside the block above the wire that was broken, pushing it upward, on top of that block.

I should probably investigate making the item drops more accurate in position and less likely to fly all over the place.
