### ISSUE TITLE
[Feature Request] Add more redstone components like latches, XOR gates and wire crossing

### ISSUE THREAD

**Issue by ButterSus** [Kneelawk/WiredRedstone#43]
Hello!

First of all, thank you for this amazing Wired-Redstone mod! It adds very useful redstone components like logic gates and data buses.
I have a few suggestions on what could be added in future versions:
- Redstone latches like T- and D-latches. They can be used for memory circuits.
- XOR/XNOR logic gates. They would extend the logic component repertoire.
- Ability to cross redstone wires (including bundled cables) without connecting them. This helps building compact circuits.
- Carry block for adders. It would allow instant carry bit transfer and speed up multi-bit adders, since currently they are slow due to ripple carry.
- Compact displays that fit up to 16 pixels and take a bus as input. This would allow building awesome displays for computing systems.

Additionally, it would be a nice polish to allow changing the texture on the edges of the data buses, since currently it results in:
![Issue](https://github.com/Kneelawk/WiredRedstone/assets/90126102/eafa1500-88b8-472a-90e4-5e6bdc9421f0)
![Crossing](https://github.com/Kneelawk/WiredRedstone/assets/90126102/1d9cb239-5a73-4085-a62f-dbfe479a255e)

These components would open up even more possibilities for advanced redstone circuits and computing systems. Please consider adding them in a future release.

**Comment by Kneelawk** [comment]
* I've been planning T-Flip-Flops and D-Latches but have not started on them yet.
* I've done some planning on potential XOR/XNOR gate designs. I'm wanting to avoid magic box designs for these simple logic gates if at all possible though, which means the rendering is getting complicated.
* I've started work on a couple things that help with crossing wires. One is powerlines, another is standing cables. Both would work here once they're completed.
* I'm not quite sure what you mean by a carry block. Do you mean like an adder gate?
* I am planning on adding a gate that shows the contents of a bundled cable. I may make a seamless standing bundled-cable display that can have a bundled cable connected to its back.
* Changing the texture on the edges of data-buses is something I have just added to the mod, as of 041ad7461adec1a269897d6f3d9c44bd9fe86b9a.

**Comment by Kneelawk** [comment]
I should hopefully have standing cables out in the next release:
![image](https://github.com/Kneelawk/WiredRedstone/assets/2180089/d3560f42-04ed-4467-bf3f-a9b09014d593)

**Comment by ButterSus** [comment]
The problem is solved with new standing wires / cables, so I'm closing this issue
