### ISSUE TITLE
If client logs out all mod blocks dissappear and can no longer be seen or interacted with

### ISSUE THREAD

**Issue by kj4lxc** [Kneelawk/WiredRedstone#47]
Currently running into an issue with this mod in this pack, https://www.curseforge.com/minecraft/modpacks/cstmgames-creative-tendencies.

When anyone on the server places any of the wires or circuit parts from this mod they work fine and then if the client logs off the server and then logs back in later they no longer render for that player and are impossible for that player to remove/interact with them at all.  Either another player has to come and break them or they have to be removed with worldedit.  I can do my best to provide any supporting data that you need.

**Comment by Kneelawk** [comment]
Wired Redstone is incompatible with Chunk Sending.

**Comment by kj4lxc** [comment]
Correct you are!  That fixed us right up!  Thanks!
