### ISSUE TITLE
Create Links don't visually connect to wires unless powered.

### ISSUE THREAD

**Issue by Aquaeyes** [Kneelawk/WiredRedstone#5]
![image](https://user-images.githubusercontent.com/10935410/171109898-625b41cd-45c5-4249-89bf-281a9b36aae8.png)
![image](https://user-images.githubusercontent.com/10935410/171109924-208ecd2a-6011-412f-b588-7ec796139ec0.png)
It's just uh, pretty much what it says on the tin. Amazing mod, and my gOD do I love the multipart support.

**Comment by Kneelawk** [comment]
I haven't actually explored Create compatibility much yet. Thanks for reporting this!

**Comment by ardissaps** [comment]
> I haven't actually explored Create compatibility much yet. Thanks for reporting this!

same with me, still function as normal and works, just minor visual glitch.
![image](https://user-images.githubusercontent.com/82106625/174959376-d8a9105e-c175-413a-b9ac-b79ca4e016e4.png)

**Comment by Kneelawk** [comment]
I have a plan to fix this one though it won't be too clean. From what I can tell, many blocks give no indication that they do anything with redstone. My plan here is to add a block-tag that specifies that a block should always be connected to by red-alloy/insulated wire.

I might eventually do something similar for bundled cable too, though that would only really be useful once I get the bundled-cable API added.

In some of these cases however, the wire is not actually supposed to connect. Uninsulated wire is designed to power all blocks around it without actually visually connecting to them. The red-alloy-wire's visual connections actually should only indicate which blocks the wire can *receive* a redstone signal from.

I don't think I'll be able to get this out in `v0.3.2` but hopefully in `v0.3.3`.

**Comment by ardissaps** [comment]
For now I just manually put additional wire on the side of the said block as it supported by lib multipart. No problem. It is only for aesthetic suggestion. But when I think more, I will just pretend (maybe the red cabble connected underground like some centimeter), just positively think about that and problem solved on my end. hahaha

**Comment by Kneelawk** [comment]
Ok, something *is* very strange with specifically Create's Redstone Links. They seem to have the ability to detect a redstone signal from a wire, even if the wire is not sending power in the Link's direction. If a wire goes near a Redstone Link, the link will receive power from it. Even if the wire is not connected to the Link (e.g. wire on the opposite side of the block from the Create Redstone Link). I'm not really sure how to fix this on my end :/

I will be working on the system to allow wires to connect to blocks with specific block-tags though which should hopefully at least fix the visual issues here.

**Comment by Kneelawk** [comment]
Ok, Wired Redstone `v0.3.3+1.18.2` has been released that incorporates the block-tags addition.

**Comment by Kneelawk** [comment]
Please let me know if you encounter any bugs with the block-tags system. :)

**Comment by ardissaps** [comment]
Thank you very much, it works. I also just figured out that Create Redstone Link cannot be rotated (can only face north), I'll report on Create.
![image](https://user-images.githubusercontent.com/82106625/176707412-5ec03491-13c9-4d34-8be5-b3682bab9bb4.png)
