### ISSUE TITLE
CC: Restiched integration doesn't fully work

### ISSUE THREAD

**Issue by 1e1001** [Kneelawk/WiredRedstone#7]
The result of `redstone.getBundledInput` will only return the first *n* `1` bits, where *n* is the number of bundled cables pointed towards the computer in the block. For example, if you have the maximum number of cables connected, 5, like so:
![image](https://user-images.githubusercontent.com/22437115/175804456-51b77168-b381-4f1a-811f-45a44d867dc4.png)
and write 0101010101010101<sub>2</sub> (5555<sub>16</sub>, or 21845<sub>10</sub>), you'll read in 0101010101000000<sub>2</sub> (5540<sub>16</sub>, or 21824<sub>10</sub>).
I believe [this line](https://github.com/Kneelawk/WiredRedstone/blob/506786ce7822583ca4d246509e78a60edd5d06c0/src/main/kotlin/com/kneelawk/wiredredstone/util/BundledCableUtils.kt#L100) might be causing the bug, using `(acc and mask.inv())` instead of `(res and mask.inv())`.

**Comment by Kneelawk** [comment]
Thanks for reporting this. I'll look into it as soon as I can.

**Comment by Kneelawk** [comment]
> I believe [this line](https://github.com/Kneelawk/WiredRedstone/blob/506786ce7822583ca4d246509e78a60edd5d06c0/src/main/kotlin/com/kneelawk/wiredredstone/util/BundledCableUtils.kt#L100) might be causing the bug, using (acc and mask.inv()) instead of (res and mask.inv()).
This does indeed look like the problem. I had the some problem while reading and fixed it there. Looks like it forgot to fix it here though.

**Comment by Kneelawk** [comment]
Ok, the fix for this has been released in `v0.3.2`.
